import AdmZip from'adm-zip';import crypto from'crypto';
function csv(t){let L=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!L.length)return[];let s=(L[0].match(/;/g)||[]).length>(L[0].match(/,/g)||[]).length?';':',';function p(l){let a=[],x='',q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c==='"'){if(q&&l[i+1]==='"'){x+='"';i++}else q=!q}else if(c===s&&!q){a.push(x);x=''}else x+=c}a.push(x);return a}let h=p(L[0]);return L.slice(1).map(l=>Object.fromEntries(p(l).map((v,i)=>[h[i],v])))}
const pick=(o,...r)=>{for(let z of r){let k=Object.keys(o).find(k=>z.test(k));if(k&&o[k])return String(o[k]).trim()}return''},N=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const money=v=>{if(!v)return null;let s=String(v).trim().replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');let n=Number(s.replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null};
const iso=v=>{let m=String(v||'').match(/^(\d{2})\/(\d{2})\/(\d{4})/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:''};
const rite=s=>N(s).includes('AUTOM')?'Automático':N(s).includes('ORDIN')?'Ordinário':s||'',aud=s=>N(s).includes('PROFISSION')?'Profissional':N(s).includes('QUALIFIC')?'Qualificado':N(s).includes('GERAL')?'Público geral':s||'';
async function load(){let m=await fetch('https://dados.cvm.gov.br/api/3/action/package_show?id=oferta-distrib',{headers:{'User-Agent':'RadarFIDC/1.1'}});if(!m.ok)throw Error('Catálogo CVM indisponível');let p=(await m.json()).result,r=[...p.resources].reverse().find(x=>/zip/i.test((x.format||'')+' '+(x.url||'')));if(!r)throw Error('ZIP CVM não encontrado');let f=await fetch(r.url);if(!f.ok)throw Error('Download CVM indisponível');let z=new AdmZip(Buffer.from(await f.arrayBuffer())),rows=[];for(let e of z.getEntries())if(/oferta_(resolucao_160|distribuicao)\.csv$/i.test(e.entryName))rows.push(...csv(e.getData().toString('utf8')).map(x=>({...x,__origin:e.entryName})));return{rows,modified:r.last_modified||p.metadata_modified}}
function item(x){let registration=pick(x,/N[ÚU]MERO.*REGISTRO/i,/NR_.*REGISTRO/i,/REGISTRO.*CVM/i),name=pick(x,/DENOMINA/i,/NOME.*OFERTA/i,/NOME.*FUNDO/i,/EMISSOR/i)||'Oferta FIDC',leader=pick(x,/COORD.*L[IÍ]DER.*NOME/i,/NOME.*COORD/i,/COORD.*L[IÍ]DER/i,/L[IÍ]DER/i,/COORDENADOR/i),leaderCnpj=pick(x,/CNPJ.*COORD/i,/COORD.*CNPJ/i),r=rite(pick(x,/RITO/i)||(/resolucao_160/i.test(x.__origin)?'Automático':'')),a=aud(pick(x,/P[ÚU]BLICO.*ALVO/i,/TIPO.*INVESTIDOR/i,/INVESTIDOR/i)),status=pick(x,/STATUS/i,/SITUA/i),date=iso(pick(x,/DATA.*REGISTRO/i,/DT_.*REGISTRO/i,/DATA.*REQUER/i,/DATA.*IN[IÍ]CIO/i)),cnpj=pick(x,/CNPJ.*FUNDO/i,/CNPJ.*EMISSOR/i,/CNPJ/i),volume=money(pick(x,/VOLUME.*OFERTA/i,/VALOR.*OFERTA/i,/MONTANTE/i,/VALOR.*TOTAL/i)),key=[registration,cnpj,name,date,volume].map(N).join('|');return{id:crypto.createHash('sha1').update(key).digest('hex').slice(0,14),name,cnpj,leader,leaderCnpj,volume,rite:r,audience:a,status,date,registration}}
const count=a=>Object.entries(a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count}));
export default async function handler(req,res){try{let{rows,modified}=await load(),raw=rows.filter(x=>Object.values(x).some(v=>/\bFIDC\b|DIREITOS CREDIT[ÓO]RIOS/i.test(String(v)))).map(item),seen=new Set(),items=[];for(let x of raw){let k=[x.registration,x.cnpj,x.name,x.date,x.volume].map(N).join('|');if(!seen.has(k)){seen.add(k);items.push(x)}}items.sort((a,b)=>String(b.date).localeCompare(String(a.date)));let dated=items.filter(x=>/^\d{4}-\d{2}/.test(x.date)),latestMonth=dated[0]?.date.slice(0,7)||null,month=latestMonth?items.filter(x=>x.date?.startsWith(latestMonth)):[],vol=month.map(x=>x.volume).filter(v=>Number.isFinite(v)&&v>0),analytics={latestMonth,offersInMonth:month.length,volumeInMonth:vol.reduce((a,b)=>a+b,0),leadersInMonth:new Set(month.map(x=>x.leader||x.leaderCnpj).filter(Boolean)).size,byRite:count(month.map(x=>x.rite||'Não informado')),byAudience:count(month.map(x=>x.audience||'Não informado')),topLeaders:count(month.map(x=>x.leader||x.leaderCnpj).filter(Boolean)).slice(0,8)};res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');res.status(200).json({source:'CVM Dados Abertos',sourceUpdatedAt:modified,rawCount:raw.length,count:items.length,analytics,items,methodology:'Registros FIDC identificados na base CVM; duplicidades exatas por registro/CNPJ/nome/data/volume são removidas. Indicadores mensais usam a competência mais recente disponível.'})}catch(e){res.status(502).json({error:e.message,source:'CVM Dados Abertos'})}}