import crypto from 'node:crypto';
import AdmZip from 'adm-zip';
import {decodeOfficialCsv,parseCsv} from './csv.js';

export const CVM_CATALOG_URL='https://dados.cvm.gov.br/api/3/action/package_show?id=oferta-distrib';
const USER_AGENT='RadarFIDC/6.0 (dados oficiais CVM)';
const clean=value=>String(value??'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim();
const normalized=value=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const digits=value=>clean(value).replace(/\D/g,'');
const validCnpj=value=>digits(value).length===14?clean(value):'';
const validDate=value=>{const input=clean(value);let m=input.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m){const br=input.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(br)m=[br[0],br[3],br[2],br[1]]}if(!m)return'';const iso=`${m[1]}-${m[2]}-${m[3]}`,date=new Date(`${iso}T00:00:00Z`);return Number.isNaN(date.valueOf())||date.toISOString().slice(0,10)!==iso?'':iso};
const validMoney=value=>{const input=clean(value);if(!input)return null;const s=input.includes(',')?input.replace(/\./g,'').replace(',','.'):input,n=Number(s.replace(/[^0-9+.-]/g,''));return Number.isFinite(n)&&n>=0?n:null};
const sha=value=>crypto.createHash('sha256').update(value).digest('hex').slice(0,16);

function isFidc(row,origin){if(origin==='resolucao160')return /^COTAS DE (FIAGRO - )?FIDC$/.test(normalized(row.Valor_Mobiliario));return[row.Tipo_Fundo_Investimento,row.Tipo_Ativo].some(value=>/(^|\b)(FIC-?FIDC|FICFIDC|FIDC)(\b|$)|DIREITOS CREDIT/.test(normalized(value)))}
function audience(value){const key=normalized(value);if(key.includes('PROFISSION'))return'Profissional';if(key.includes('QUALIFIC'))return'Qualificado';if(key.includes('PUBLICO GERAL')||key.includes('PUBLICO EM GERAL'))return'Público geral';return clean(value)}
function rite(value){const key=normalized(value);if(key.includes('AUTOM'))return'Automático';if(key.includes('ORDIN'))return'Ordinário';if(key.includes('ICVM 476'))return'ICVM 476';if(key.includes('ICVM 555'))return'ICVM 555';if(key.includes('ICVM 400'))return'ICVM 400';return clean(value)}

function rowToComponent(row,origin){
 const automatic=origin==='resolucao160',officialNumber=clean(automatic?row.Numero_Requerimento:row.Numero_Registro_Oferta),processNumber=clean(row.Numero_Processo),cnpj=validCnpj(row.CNPJ_Emissor),name=clean(row.Nome_Emissor);
 const registrationDate=validDate(automatic?row.Data_Registro:row.Data_Registro_Oferta),requestDate=validDate(automatic?row.Data_requerimento:row.Data_Protocolo)||validDate(row.Data_Abertura_Processo),date=registrationDate||requestDate,dateBasis=registrationDate?'registro':requestDate?'requerimento':'';
 const volume=validMoney(automatic?row.Valor_Total_Registrado:row.Valor_Total),leaderCnpj=validCnpj(row.CNPJ_Lider),leader=clean(row.Nome_Lider),security=clean(automatic?row.Valor_Mobiliario:row.Tipo_Ativo);
 const componentKey=automatic?(officialNumber||[processNumber,cnpj,date,volume].join('|')):[officialNumber,processNumber,clean(row.Emissao),clean(row.Classe_Ativo),clean(row.Serie),security,volume].join('|');
 const offerKey=automatic?`R160:${officialNumber||processNumber||sha([cnpj,name,date].join('|'))}`:`DISTRIB:${officialNumber||processNumber||sha([cnpj,name,date].join('|'))}`;
 return{offerKey,componentKey,officialNumber,processNumber,cnpj,name,leader,leaderCnpj,volume,date,dateBasis,security,rite:rite(automatic?row.Rito_Requerimento:row.Rito_Oferta),audience:audience(automatic?row.Publico_alvo:''),status:clean(automatic?row.Status_Requerimento:row.Modalidade_Registro||row.Modalidade_Oferta),sourceFile:automatic?'oferta_resolucao_160.csv':'oferta_distribuicao.csv'};
}
function chooseText(values){const counts=new Map();values.map(clean).filter(Boolean).forEach(value=>counts.set(value,(counts.get(value)||0)+1));return[...counts.entries()].sort((a,b)=>b[1]-a[1]||b[0].length-a[0].length)[0]?.[0]||''}
function mergeOffer(components){const unique=new Map();for(const component of components)if(!unique.has(component.componentKey))unique.set(component.componentKey,component);const rows=[...unique.values()],base=rows[0],volumes=rows.map(row=>row.volume).filter(Number.isFinite),selectedDate=rows.filter(row=>row.date).sort((a,b)=>b.date.localeCompare(a.date))[0],leaderCnpj=chooseText(rows.map(row=>row.leaderCnpj));return{id:sha(base.offerKey),name:chooseText(rows.map(row=>row.name))||'Oferta FIDC sem denominação informada',cnpj:chooseText(rows.map(row=>row.cnpj)),registration:chooseText(rows.map(row=>row.officialNumber)),processNumber:chooseText(rows.map(row=>row.processNumber)),leader:chooseText(rows.filter(row=>!leaderCnpj||digits(row.leaderCnpj)===digits(leaderCnpj)).map(row=>row.leader))||chooseText(rows.map(row=>row.leader)),leaderCnpj,volume:volumes.length?volumes.reduce((sum,value)=>sum+value,0):null,volumeComponents:volumes.length,rite:chooseText(rows.map(row=>row.rite)),audience:chooseText(rows.map(row=>row.audience)),status:chooseText(rows.map(row=>row.status)),date:selectedDate?.date||'',dateBasis:selectedDate?.dateBasis||'',securities:[...new Set(rows.map(row=>row.security).filter(Boolean))],sourceFile:base.sourceFile,sourceRows:components.length,distinctComponents:rows.length}}
function countBy(values){const counts=new Map();values.filter(Boolean).forEach(value=>counts.set(value,(counts.get(value)||0)+1));return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'pt-BR')).map(([name,count])=>({name,count}))}
function coordinatorAnalytics(items){const groups=new Map();for(const item of items){const key=item.leaderCnpj?`CNPJ:${digits(item.leaderCnpj)}`:item.leader?`NOME:${normalized(item.leader)}`:'';if(!key)continue;const current=groups.get(key)||{names:[],cnpj:item.leaderCnpj,count:0,volume:0};current.names.push(item.leader);current.count+=1;if(Number.isFinite(item.volume))current.volume+=item.volume;groups.set(key,current)}return[...groups.values()].map(group=>({name:chooseText(group.names)||group.cnpj,cnpj:group.cnpj,count:group.count,volume:group.volume})).sort((a,b)=>b.count-a.count||b.volume-a.volume||a.name.localeCompare(b.name,'pt-BR'))}

export function buildCvmDataset(inputRows,sourceUpdatedAt){
 const components=inputRows.filter(({row,origin})=>isFidc(row,origin)).map(({row,origin})=>rowToComponent(row,origin)),offers=new Map();
 for(const component of components){const list=offers.get(component.offerKey)||[];list.push(component);offers.set(component.offerKey,list)}
 const items=[...offers.values()].map(mergeOffer).sort((a,b)=>b.date.localeCompare(a.date)||a.name.localeCompare(b.name,'pt-BR')),latestMonth=items.find(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date))?.date.slice(0,7)||null,month=latestMonth?items.filter(item=>item.date.startsWith(latestMonth)):[],monthVolumes=month.map(item=>item.volume).filter(Number.isFinite),leaders=coordinatorAnalytics(month);
 return{source:'CVM Dados Abertos — Ofertas Públicas de Distribuição',sourceUrl:'https://dados.cvm.gov.br/dataset/oferta-distrib',sourceUpdatedAt,rawFidcRows:components.length,count:items.length,analytics:{latestMonth,offersInMonth:month.length,volumeInMonth:monthVolumes.reduce((sum,value)=>sum+value,0),offersWithVolumeInMonth:monthVolumes.length,leadersInMonth:leaders.length,byRite:countBy(month.map(item=>item.rite||'Não informado')),byAudience:countBy(month.map(item=>item.audience||'Não informado')),topLeaders:leaders.slice(0,8)},items,methodology:'Ofertas FIDC identificadas pelos campos oficiais Tipo_Fundo_Investimento/Tipo_Ativo e Valor_Mobiliario. Linhas de classes ou séries são consolidadas pelo número oficial da oferta ou processo; volumes somam somente componentes distintos. A competência usa a data de registro e, quando ausente, a data do requerimento/protocolo.'};
}

export async function fetchCvmDataset(fetchImpl=fetch){
 const metadataResponse=await fetchImpl(CVM_CATALOG_URL,{headers:{'User-Agent':USER_AGENT,Accept:'application/json'}});if(!metadataResponse.ok)throw new Error(`CVM catálogo indisponível: HTTP ${metadataResponse.status}`);const metadata=await metadataResponse.json(),pkg=metadata?.result;if(!pkg||!Array.isArray(pkg.resources))throw new Error('Resposta inválida do catálogo CVM');
 const resource=pkg.resources.find(item=>/ofertas de distribui/i.test(item.name||'')&&/zip/i.test(`${item.format||''} ${item.url||''}`));if(!resource?.url)throw new Error('Recurso oficial de ofertas da CVM não encontrado');const dataResponse=await fetchImpl(resource.url,{headers:{'User-Agent':USER_AGENT,Accept:'application/zip'}});if(!dataResponse.ok)throw new Error(`Download CVM indisponível: HTTP ${dataResponse.status}`);
 const zip=new AdmZip(Buffer.from(await dataResponse.arrayBuffer())),inputRows=[];for(const[fileName,origin]of[['oferta_distribuicao.csv','distribuicao'],['oferta_resolucao_160.csv','resolucao160']]){const entry=zip.getEntries().find(candidate=>candidate.entryName.toLowerCase().endsWith(fileName));if(!entry)throw new Error(`Arquivo obrigatório ausente no ZIP CVM: ${fileName}`);const rows=parseCsv(decodeOfficialCsv(entry.getData()));if(!rows.length)throw new Error(`Arquivo oficial CVM vazio ou inválido: ${fileName}`);rows.forEach(row=>inputRows.push({row,origin}))}
 return buildCvmDataset(inputRows,resource.last_modified||pkg.metadata_modified||null);
}
