const DAY=86400000;
const clean=v=>String(v||'').trim();
const digits=v=>clean(v).replace(/\D/g,'');
const finite=v=>Number.isFinite(v);
const positive=v=>finite(v)&&v>0;
const monthOf=item=>/^\d{4}-\d{2}-\d{2}$/.test(item?.date||'')?item.date.slice(0,7):'';
const monthEnd=month=>new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0,23,59,59));
const quantile=(values,q)=>{const a=values.filter(finite).sort((x,y)=>x-y);if(!a.length)return null;const p=(a.length-1)*q,i=Math.floor(p),f=p-i;return a[i]+(a[i+1]!==undefined?(a[i+1]-a[i])*f:0)};
export const percentileRank=(value,values)=>{const a=values.filter(finite);if(!finite(value)||!a.length)return null;if(a.length===1)return 50;const less=a.filter(x=>x<value).length,equal=a.filter(x=>x===value).length;return Math.max(0,Math.min(100,((less+0.5*equal)/a.length)*100))};
const avg=values=>{const a=values.filter(finite);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null};
const coordinatorKey=x=>digits(x.leaderCnpj)||clean(x.leader).toUpperCase();
const issuerKey=x=>digits(x.cnpj)||clean(x.name).toUpperCase();
const rowsForMonth=(items,month)=>items.filter(x=>monthOf(x)===month);
const monthMetric=(items,month)=>{const rows=rowsForMonth(items,month),vol=rows.filter(x=>positive(x.volume)).map(x=>x.volume);return{month,count:rows.length,volume:vol.reduce((s,x)=>s+x,0),withVolume:vol.length,coordinators:new Set(rows.map(coordinatorKey).filter(Boolean)).size,issuers:new Set(rows.map(issuerKey).filter(Boolean)).size,medianTicket:quantile(vol,.5)}};
function listMonths(endMonth,n=12){const d=new Date(`${endMonth}-01T00:00:00Z`),out=[];for(let i=n-1;i>=0;i--){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()-i,1));out.push(x.toISOString().slice(0,7))}return out}
function normHHI(shares){const a=shares.filter(x=>finite(x)&&x>0),n=a.length;if(n<=1)return n===1?100:0;const sum=a.reduce((s,x)=>s+x,0);if(!sum)return 0;const h=a.reduce((s,x)=>s+(x/sum)**2,0),min=1/n;return Math.max(0,Math.min(100,(h-min)/(1-min)*100))}
function concentration(items,month){const rows=rowsForMonth(items,month),byCount=new Map(),byVol=new Map();for(const x of rows){const k=coordinatorKey(x);if(!k)continue;byCount.set(k,(byCount.get(k)||0)+1);if(positive(x.volume))byVol.set(k,(byVol.get(k)||0)+x.volume)}const countScore=normHHI([...byCount.values()]),volumeScore=normHHI([...byVol.values()]);return{score:avg([countScore,volumeScore]),countHHI:countScore,volumeHHI:volumeScore,interpretation:avg([countScore,volumeScore])>=67?'alta':avg([countScore,volumeScore])>=34?'moderada':'baixa'}}
function selectSeriesAtOrBefore(series,month){const limit=monthEnd(month);return(series?.history||[]).filter(x=>new Date(x.date+'T00:00:00Z')<=limit).sort((a,b)=>a.date.localeCompare(b.date))}
function fundingConditions(bcb,month){if(!bcb?.series)return{score:null,components:[],asOf:null};const specs=[['selic','Selic',true,.3],['spreadPJ','Spread PJ',true,.3],['inadPJ','Inadimplência PJ',true,.2]],parts=[];for(const[key,label,invert,weight]of specs){const h=selectSeriesAtOrBefore(bcb.series[key],month);if(!h.length)continue;const cur=h.at(-1),rank=percentileRank(cur.value,h.map(x=>x.value));parts.push({key,label,value:cur.value,date:cur.date,score:invert?100-rank:rank,weight})}const credit=selectSeriesAtOrBefore(bcb.series.estoquePJ,month);if(credit.length>=4){const changes=[];for(let i=3;i<credit.length;i++)changes.push((credit[i].value/credit[i-3].value-1)*100);const current=changes.at(-1),rank=percentileRank(current,changes);parts.push({key:'credito3m',label:'Crescimento 3m do saldo PJ',value:current,date:credit.at(-1).date,score:rank,weight:.2})}const w=parts.reduce((s,x)=>s+x.weight,0),score=w?parts.reduce((s,x)=>s+x.score*x.weight,0)/w:null;return{score,components:parts,asOf:parts.map(x=>x.date).sort().at(-1)||null,interpretation:score===null?'indisponível':score>=67?'favoráveis':score>=34?'neutras/medianas':'restritivas'}}
function offeringPressure(items,month){const months=listMonths(month,12),metrics=months.map(m=>monthMetric(items,m)),cur=metrics.at(-1),countScore=percentileRank(cur.count,metrics.map(x=>x.count)),volumeScore=percentileRank(cur.volume,metrics.map(x=>x.volume)),coordScore=percentileRank(cur.coordinators,metrics.map(x=>x.coordinators)),issuerScore=percentileRank(cur.issuers,metrics.map(x=>x.issuers)),breadth=avg([coordScore,issuerScore]),score=.4*volumeScore+.35*countScore+.25*breadth;return{score,countScore,volumeScore,breadthScore:breadth,metric:cur,history:metrics,interpretation:score>=67?'forte':score>=34?'intermediária':'fraca'}}
function annualScenarios(items,month){const year=month.slice(0,4),monthNum=Number(month.slice(5,7)),months=listMonths(month,12),hist=months.map(m=>monthMetric(items,m)),ytd=items.filter(x=>monthOf(x)>=`${year}-01`&&monthOf(x)<=month),actualVolume=ytd.filter(x=>positive(x.volume)).reduce((s,x)=>s+x.volume,0),actualOffers=ytd.length,remaining=12-monthNum,vols=hist.map(x=>x.volume),counts=hist.map(x=>x.count),qv=[quantile(vols,.25),quantile(vols,.5),quantile(vols,.75)],qc=[quantile(counts,.25),quantile(counts,.5),quantile(counts,.75)],build=(label,i)=>({label,volume:actualVolume+(qv[i]||0)*remaining,offers:Math.round(actualOffers+(qc[i]||0)*remaining),monthlyVolumeAssumption:qv[i],monthlyOfferAssumption:qc[i]});return{year:Number(year),actualThrough:month,actualVolume,actualOffers,remainingMonths:remaining,scenarios:[build('Conservador',0),build('Base',1),build('Expansão',2)],method:'Realizado no ano + p25/mediana/p75 dos 12 meses encerrados no mês de referência para os meses restantes. Cenários de ritmo, não previsão de captação efetiva.'}}
export function computeMarketIndices(items,bcb,month){const offer=offeringPressure(items,month),conc=concentration(items,month),fund=fundingConditions(bcb,month),pulse=fund.score===null?offer.score:.7*offer.score+.3*fund.score;return{month,offerPressure:{code:'IROP',name:'Índice Radar de Oferta Primária',score:offer.score,components:{volume:offer.volumeScore,quantity:offer.countScore,breadth:offer.breadthScore},interpretation:offer.interpretation},breadth:{code:'IRBD',name:'Índice Radar de Breadth',score:offer.breadthScore,interpretation:offer.breadthScore>=67?'ampla':offer.breadthScore>=34?'mediana':'estreita'},concentration:{code:'IRCC',name:'Índice Radar de Concentração',...conc},funding:{code:'IRFC',name:'Índice Radar de Condições de Funding',...fund},pulse:{code:'IRPM',name:'Índice Radar de Pulso de Mercado',score:pulse,interpretation:pulse>=67?'expansivo':pulse>=34?'equilibrado':'contido'},projection:annualScenarios(items,month),methodology:'Escala 0-100. IROP usa percentis dos últimos 12 meses: 40% volume registrado, 35% quantidade de ofertas e 25% breadth (emissores/coordenadores). IRCC usa HHI normalizado por quantidade e volume. IRFC combina Selic, spread PJ, inadimplência PJ e crescimento trimestral do saldo de crédito PJ, reponderando componentes disponíveis. IRPM = 70% IROP + 30% IRFC. Volume registrado não equivale a captação efetiva.'}}
export function computeRadarIndices(dataset,bcb,month){const markets={};for(const key of ['FIDC','FIAGRO','FII'])markets[key]=computeMarketIndices(dataset.markets[key].items,bcb,month);markets.ALL=computeMarketIndices(dataset.allItems,bcb,month);return{month,markets,generatedAt:new Date().toISOString()}}
